server:
  port: 8085

dubbo:
  application:
    name: Caiyu-Health-Consumer # dubbo 应用名称
  registry: # zookeeper 集群注册中心地址
    address: zookeeper://127.0.0.1:2181


spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 5

    connect-timeout: 1000
  session:
    store-type: none
